from .AT import Attention
from .CC import Correlation
from .FitNet import HintLoss
from .KD import DistillKL
from .PKT import PKT
from .RKD import RKDLoss
from .SP import Similarity
from .VID import VIDLoss
from .IRG import IRGLoss
from .SemCKD import SemCKDLoss
from .HKD import HKDLoss
